### ISSUE TITLE
traine model    AttributeError: 'DiffusionDet' object has no attribute 'q_sample'

### ISSUE THREAD

**Issue by Aruen24** [ShoufaChen/DiffusionDet#1]
AttributeError: 'DiffusionDet' object has no attribute 'q_sample'

**Comment by ShoufaChen** [comment]
Hi, thanks for your interest.
It seems that we deleted this function when clean the code.

Fixed in https://github.com/ShoufaChen/DiffusionDet/commit/423d3574d27157d7f622193be9ce216863559a58
Please use the latest code.

**Comment by ShoufaChen** [comment]
Hi, @Aruen24,

this issue is closed automatically. Feel free to re-open it if it doesn't solve your problem.

**Comment by Aruen24** [comment]
@ShoufaChen 
ok, It has solved the problem.
