### ISSUE TITLE
Sample step

### ISSUE THREAD

**Issue by chouqin3** [ShoufaChen/DiffusionDet#19]
https://github.com/ShoufaChen/DiffusionDet/blob/1efb36d4b0b721f2d509bc72656235a94d73ab02/diffusiondet/config.py#L52

Why the time step is set to be 1, the time pairs becomes {999, -1},  as shown below. In the report, it is set to [{T-1, T-2}, {T-2, T-3} ... ]. Please explain it.
![image](https://user-images.githubusercontent.com/12481496/204741152-8a3f403f-fbb8-400f-ab32-2fecb38c3c2a.png)

**Comment by ShoufaChen** [comment]
Hi,

Thanks for your interest.

We use *DDIM* sampling method. At the sampling stage, the total number of steps, $T=1000$ in our case, is evenly divided by the number of sampling steps.

**Comment by chouqin3** [comment]
Thank you for the timely reply.

**Comment by vadimkantorov** [comment]
@ShoufaChen The paper mentions that best results at 8 refinement/diffusion steps at sampling time. Does it mean that for repro of those results we must set `SAMPLE_STEP = 8`?

**Comment by ShoufaChen** [comment]
Hi, @vadimkantorov ,

The results presented https://github.com/ShoufaChen/DiffusionDet#models are evaluated with `SAMPLE_STEP = 1`.
