### ISSUE TITLE
Feature Request: Adding prediction(detect.py) code

### ISSUE THREAD

**Issue by kadirnar** [ShoufaChen/DiffusionDet#2]
Hello,

I'm curious about the prediction results of this project. Will you share the detect.py file?

**Comment by ShoufaChen** [comment]
Hi,

Thanks for your interest in our work.

Do you mean evaluation?

You can evaluate DiffusionDet following "**5 Evaluate DiffusionDet**" in https://github.com/ShoufaChen/DiffusionDet/blob/main/GETTING_STARTED.md.

**Comment by kadirnar** [comment]
Thank you for return. I want to make a prediction using an image or video. Should I try these codes?
https://github.com/ShoufaChen/DiffusionDet/blob/main/diffusiondet/detector.py#L434-L476

Examples:
Yolov5: https://github.com/ultralytics/yolov5/blob/master/detect.py
Yolov6: https://github.com/meituan/YOLOv6/blob/main/yolov6/core/inferer.py
YOLOX: https://github.com/Megvii-BaseDetection/YOLOX/blob/main/tools/demo.py

**Comment by kadirnar** [comment]
Thank you for return. I want to make a prediction using an image or video. Should I try these codes?
https://github.com/ShoufaChen/DiffusionDet/blob/main/diffusiondet/detector.py#L434-L476

Examples:
Yolov5: https://github.com/ultralytics/yolov5/blob/master/detect.py
Yolov6: https://github.com/meituan/YOLOv6/blob/main/yolov6/core/inferer.py
YOLOX: https://github.com/Megvii-BaseDetection/YOLOX/blob/main/tools/demo.py

**Comment by ShoufaChen** [comment]
Hi, @kadirnar ,

We provide a demo tool at https://github.com/ShoufaChen/DiffusionDet/pull/3.

You can have a try following [Inference Demo with Pre-trained Models](https://github.com/ShoufaChen/DiffusionDet/blob/main/GETTING_STARTED.md#inference-demo-with-pre-trained-models).

**Comment by kadirnar** [comment]
Thank you so much.
