### ISSUE TITLE
what does this "3sigma == 1/2 , ---> sigma: 1/6" mean?

### ISSUE THREAD

**Issue by hzy312** [ShoufaChen/DiffusionDet#21]
https://github.com/ShoufaChen/DiffusionDet/blob/1efb36d4b0b721f2d509bc72656235a94d73ab02/diffusiondet/detector.py#L385

what does this "3sigma == 1/2 , ---> sigma: 1/6" mean?
can you help for explaining this?

**Comment by LMD0311** [comment]
Can you explain this? I am confusing about this.

**Comment by zifuwan** [comment]
Hi, I am also confused by this "3sigma == 1/2 , ---> sigma: 1/6", have you figured out the meaning?

**Comment by LMD0311** [comment]
> Hi, I am also confused by this "3sigma == 1/2 , ---> sigma: 1/6", have you figured out the meaning?

@Jeff001128 I believe it uses the 3sigma principle to transform values to between 0 and 1

**Comment by zifuwan** [comment]
@LMD0311 Thanks a lot !
