### ISSUE TITLE
Detectron2 Installation

### ISSUE THREAD

**Issue by mmaaz60** [ShoufaChen/DiffusionDet#22]
Thank you for the great work. I was trying to run LVIS model training and getting the following error,

`ImportError: cannot import name 'get_fed_loss_cls_weights' from 'detectron2.data.detection_utils'`

I am using PyTorch==1.10.0 and Detectron2==0.6 with CUDA 11.1. I installed Detectron2 from the pre-built libraries.

**Comment by ShoufaChen** [comment]
Hi,

Thanks for your interest.

I think installing the nightly Detectron2 from source could solve this problem.
Following:
https://github.com/facebookresearch/detectron2/blob/main/INSTALL.md#build-detectron2-from-source

**Comment by mmaaz60** [comment]
> Hi,
> 
> Thanks for your interest.
> 
> I think installing the nightly Detectron2 from source could solve this problem. Following: https://github.com/facebookresearch/detectron2/blob/main/INSTALL.md#build-detectron2-from-source

Hi @ShoufaChen,

Thank you. It worked. However now I am facing another issue. Looks like the error with LVIS package. Any comments? What versions did you use exactly for lvis and OpenCV packages? Thanks

![image](https://user-images.githubusercontent.com/55104795/205272146-fb6ea67a-80e8-468d-9596-a2a547a382d0.png)

**Comment by ShoufaChen** [comment]
FYI:
LVIS: 0.5.3
opencv-python: 4.6.0.66
