### ISSUE TITLE
 What's the usage of GaussianFourierProjection?

### ISSUE THREAD

**Issue by Naruto-Sasuke** [ShoufaChen/DiffusionDet#24]
Hi, thank you for your interesting work!

I wonder that's the usage of this function.

I notice `SinusoidalPositionEmbeddings` is used to encode time embeddings.

then, if I want to apply time embeddings into the spatial feature maps (ie,  N*C*H*W)， how can I achieve it ? It seems I cannot directly use `SinusoidalPositionEmbeddings`.

**Comment by ShoufaChen** [comment]
Hi,

Thanks for your interest in our work.

Applying time embeddings into the spatial feature is implemented in https://github.com/ShoufaChen/DiffusionDet/blob/main/diffusiondet/head.py#L271-L274.

Please have a check.

**Comment by Naruto-Sasuke** [comment]
Such embedding method is quite interesting and reasonable, thank you!
