### ISSUE TITLE
Does any words about `self.use_ensemble` shown in the paper?

### ISSUE THREAD

**Issue by Naruto-Sasuke** [ShoufaChen/DiffusionDet#26]
https://github.com/ShoufaChen/DiffusionDet/blob/1efb36d4b0b721f2d509bc72656235a94d73ab02/diffusiondet/detector.py#L239

Can you explain what's the propose of  `use_ensemble`  and how it works for better performance? Many thanks!

**Comment by ShoufaChen** [comment]
Hi,

Thanks for your interest.

Please see Table 4 in our paper for the discussion of the ensemble.
