### ISSUE TITLE
Question about the targets format / prepare_targets / self.head

### ISSUE THREAD

**Issue by vadimkantorov** [ShoufaChen/DiffusionDet#27]
Hi!

Could you please elaborate a bit on the format of `outputs_coord` returned by `self.head`? and the format of targets returned by `prepare_targets`?

In training, it seems that it's predicting the new boxes coordinates in absolute coordinates, given previous iteration's estimate. The loss is applied on those `outputs_coord`, and the loss seems to compare it not to noises, but always to ground truth boxes: https://github.com/ShoufaChen/DiffusionDet/blob/main/diffusiondet/loss.py#L180-L181. `noises` return value from `prepare_targets` seems discarded

Am I correct? Basically trying to understand how the box prediction is parametrized. Is it because the RCNNhead reapplies the predicted deltas/shift before returning its value?

Another question is on the `DynamicHead`: am I correct that at every step of diffusion inside the head it already does `NUM_HEADS = 6` rounds of refinement via `self.head_series` which consists of `RCNNHead` instances?

Thanks!

**Comment by ShoufaChen** [comment]
Hi,

Thanks for your interest in our work.

1. `outputs_coord`: predict boxes: absolute coordinates (x1, y1, x2, y2)
2. Noises are added to boxes in https://github.com/ShoufaChen/DiffusionDet/blob/main/diffusiondet/detector.py#L398
3. Yes, a single step contains 6 stages, following DETR, Deformable DETR, etc.

**Comment by vadimkantorov** [comment]
Thanks!
