### ISSUE TITLE
`self.objective` seems not used

### ISSUE THREAD

**Issue by Naruto-Sasuke** [ShoufaChen/DiffusionDet#28]
https://github.com/ShoufaChen/DiffusionDet/blob/1efb36d4b0b721f2d509bc72656235a94d73ab02/diffusiondet/detector.py#L190

**Comment by ShoufaChen** [comment]
Good catch! Thank you.

`objective` can be predicting $x_0$ and or added noise. We use $x_0$ in this work.

More details can be found in https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L544-L552.
