### ISSUE TITLE
A bug ? Seems you use `x_start` of the last instance prediction as the prediction `x_start` of the whole batch

### ISSUE THREAD

**Issue by Naruto-Sasuke** [ShoufaChen/DiffusionDet#29]
https://github.com/ShoufaChen/DiffusionDet/blob/1efb36d4b0b721f2d509bc72656235a94d73ab02/diffusiondet/detector.py#L177

`x_start = outputs_coord[-1]` makes me confused, and you guys predict `z_t` using the last prediction in the batch, why?

**Comment by ShoufaChen** [comment]
Hi,

We predict $x_0$ instead of $z_t$.

**Comment by Naruto-Sasuke** [comment]
Yes, I mean that predict `z_t` using `self.predict_noise_from_start(x, t, x_start)`, however `x_start = outputs_coord[-1]` means you only use the last prediction of `self.head` in a batch.

**Comment by ShoufaChen** [comment]
Sorry for your misunderstanding.

It is the output from the last stage of the detection head, not the last example of a batch.

**Comment by Naruto-Sasuke** [comment]
Reasonable!
