### ISSUE TITLE
[A Bug?] The diffused boxes as input may have negative coordinates. 

### ISSUE THREAD

**Issue by YTEP-ZHI** [ShoufaChen/DiffusionDet#33]
https://github.com/ShoufaChen/DiffusionDet/blob/1efb36d4b0b721f2d509bc72656235a94d73ab02/diffusiondet/detector.py#L400-L403

Though you clamped the coordinates (x) at line400, they may become negative number when converted from (cx, cy, w, h) to (x, y, x, y) mode. Here is an example:

![image](https://user-images.githubusercontent.com/48089846/207562633-0bea26fd-ce9d-4693-a7aa-d34d7a5514af.png)

It happens when cx or cy is close to zero (or clamped to zero), if conducting cx - w/2 or cy - h/2,  it becomes negative number.

Is it acceptable to pass the negative coordinates to the RCNN head?  Will it cause any unexpected behavior extracting roi feature?

**Comment by ShoufaChen** [comment]
Hi,

Thanks for your interest.

Yes, the RCNN head can accept negative coordinates.

**Comment by YTEP-ZHI** [comment]
Thanks for your reply.
