### ISSUE TITLE
missing module create_ddp_model

### ISSUE THREAD

**Issue by bravezzzzzz** [ShoufaChen/DiffusionDet#4]
Hi, thanks for the wonderful work!  Could you please provide the code of "create_ddp_model" in detectron2.engine, which is used in [train_net.py](https://github.com/ShoufaChen/DiffusionDet/blob/main/train_net.py) at line 29?

**Comment by ShoufaChen** [comment]
Hi,

`creat_ddp_model` can be found in https://github.com/facebookresearch/detectron2/blob/main/detectron2/engine/defaults.py#L60.
