### ISSUE TITLE
Performance about DiffusionDet with SwinLarge

### ISSUE THREAD

**Issue by zhangxgu** [ShoufaChen/DiffusionDet#42]
Hi, I wander to know whether I can perform diffusiondet with SwinLarge as backbone? How or where do you get the pretrained wegihts of SwinBase? 
Thanks a lot !

**Comment by ShoufaChen** [comment]
Hi,

We didn't test with SwinLarge. 

SwinBase can be found https://github.com/ShoufaChen/DiffusionDet/releases/download/v0.1/diffdet_lvis_swinbase.pth.

**Comment by zhangxgu** [comment]
Hi, is the swinbase pretrained weight from https://github.com/microsoft/Swin-Transformer ?
![image](https://user-images.githubusercontent.com/20377534/209417586-5e4f4cbf-ba28-4577-a5d3-08e97425063a.png)

**Comment by ShoufaChen** [comment]
Yes, more details can be found in https://github.com/ShoufaChen/DiffusionDet/blob/main/GETTING_STARTED.md#steps.

**Comment by zhangxgu** [comment]
Hi, the weights of SwinL from microsoft are ended with ".pth" while your SwinB weights are ended with '.pkl'. Have you ever changed some names of swin parameters for loading weights?  Directly loading microsoft Swin-L weights will lead to more mismatch in the log.
![image](https://user-images.githubusercontent.com/20377534/209419753-43d5cfb1-bce1-4e8b-b088-9f89476a0ae7.png)
Hope for your help.

**Comment by ShoufaChen** [comment]
Please use this script: https://github.com/facebookresearch/Detic/blob/main/tools/convert-thirdparty-pretrained-model-to-d2.py to convert the checkpoint format.
