### ISSUE TITLE
How the detection heads work?

### ISSUE THREAD

**Issue by cocoshe** [ShoufaChen/DiffusionDet#47]
Why using so many rcnn heads(default 6 heads) [here](https://github.com/ShoufaChen/DiffusionDet/blob/1efb36d4b0b721f2d509bc72656235a94d73ab02/diffusiondet/head.py#L163)? If I only use less head or just one head, would it work well? Any references about this part can I learn?

**Comment by ShoufaChen** [comment]
Hi,

Thanks for your interest.

We didn't conduct related ablation studies in this work. However, you can find similar experiments in [Sparse R-CNN](https://openaccess.thecvf.com/content/CVPR2021/papers/Sun_Sparse_R-CNN_End-to-End_Object_Detection_With_Learnable_Proposals_CVPR_2021_paper.pdf) Table 8.

**Comment by cocoshe** [comment]
Thanks for your reply
