### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by jxhuang0508** [ShoufaChen/DiffusionDet#5]
Hi,

Thanks for sharing your great work. May I know the training time of each model if possible?

Many thanks!

**Comment by ericzw** [comment]
same question... ^_^

**Comment by ShoufaChen** [comment]
Hello, it takes about 39 hours on 8xA100 for [DiffusionDet-COCO-Res50](https://github.com/ShoufaChen/DiffusionDet/blob/main/configs/diffdet.coco.res50.yaml).

**Comment by leemengwei** [comment]
> Hello, it takes about 39 hours on 8xA100 for [DiffusionDet-COCO-Res50](https://github.com/ShoufaChen/DiffusionDet/blob/main/configs/diffdet.coco.res50.yaml).

Hi  may I know the inference time of each image?  for example on 640x640x3 image

**Comment by ShoufaChen** [comment]
Hi @leemengwei ,

We report latency in Table 3 (f) https://arxiv.org/pdf/2211.09788.pdf.

Wish this table could solve your concern.

**Comment by leemengwei** [comment]
@ShoufaChen  thanks4 reply
Yet as metioned in paper:  "The run time is evaluated on a single NVIDIA A100 GPU with a mini-batch size of 1" which achieves about 30fps  .... I can say this is not yet something for everyone to use on PC ...

**Comment by jxhuang0508** [comment]
> Hello, it takes about 39 hours on 8xA100 for [DiffusionDet-COCO-Res50](https://github.com/ShoufaChen/DiffusionDet/blob/main/configs/diffdet.coco.res50.yaml).

Thanks for your information.

**Comment by mmaaz60** [comment]
> Hello, it takes about 39 hours on 8xA100 for [DiffusionDet-COCO-Res50](https://github.com/ShoufaChen/DiffusionDet/blob/main/configs/diffdet.coco.res50.yaml).

Hi @ShoufaChen ,

What is the estimated training time for R50 LVIS model? Thanks
