### ISSUE TITLE
How many steps is DiffusionDet used in training process?

### ISSUE THREAD

**Issue by caihaunqai** [ShoufaChen/DiffusionDet#57]
Thank you for your excellent job. I find that it can use only one sampling step when testing. But for most diffusion models, need many steps and some are trained using 1000 steps or even more. I wonder how many steps is DiffusionDet used in the training process and why it can only use 1 step when testing. Thank you.

**Comment by ShoufaChen** [comment]
Hi,

Thanks for your interest.

We use DDIM sampling methods, which can use different sampling steps at the evaluation stage from training.
