### ISSUE TITLE
What does ``deep_supervision'' mean ?

### ISSUE THREAD

**Issue by ghost** [ShoufaChen/DiffusionDet#58]
I notice that there is a parameter named ``deep_supervision`` in your code. Actually, when set ``deep_supervision = Ture``, it calculates the loss among all the features of ROI head. Can I set ``deep_supervision = False``? Is this setting harms the final results?

**Comment by ShoufaChen** [comment]
Hi,

There are 6 stages in our detection head, following DETR and Sparse R-CNN. When `deep_supervision = Ture`, these 6 heads are all supervised by the ground truth.

Yes, `deep_supervision = False` would harm the performance significantly.
