### ISSUE TITLE
What does  torch.randn() / 6 + 0.5 mean?

### ISSUE THREAD

**Issue by luluho1208** [ShoufaChen/DiffusionDet#59]
Hi, thanks for your great work!

I don't really understand why we need to / 6 + 0.5 when doing the box_placeholder random.
Also your comment in the code # 3sigma = 1/2 --> sigma: 1/6.
Can you explain more?  Thanks in advanced!

CJ

**Comment by ShoufaChen** [comment]
Hi,

Please refer to https://github.com/ShoufaChen/DiffusionDet/issues/21.

**Comment by luluho1208** [comment]
Got it! Thank you for your quick response.
