### ISSUE TITLE
The meaning of "shift" here, and why you need "shift" and "scale"?

### ISSUE THREAD

**Issue by cocoshe** [ShoufaChen/DiffusionDet#64]
https://github.com/ShoufaChen/DiffusionDet/blob/1efb36d4b0b721f2d509bc72656235a94d73ab02/diffusiondet/head.py#L271-L274

**Comment by ShoufaChen** [comment]
Hi,

This implementation is borrowed from:

https://github.com/lucidrains/denoising-diffusion-pytorch/blob/2f85f7a88003f038b19b4d703b4009dc4cd1bfe9/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L180-L182

You can find a discussion here: https://github.com/lucidrains/denoising-diffusion-pytorch/issues/77

**Comment by cocoshe** [comment]
> Hi,
> 
> This implementation is borrowed from:
> 
> https://github.com/lucidrains/denoising-diffusion-pytorch/blob/2f85f7a88003f038b19b4d703b4009dc4cd1bfe9/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L180-L182
> 
> You can find a discussion here: [lucidrains/denoising-diffusion-pytorch#77](https://github.com/lucidrains/denoising-diffusion-pytorch/issues/77)

Thanks for your instruction!
