### ISSUE TITLE
About the shape of roi_features

### ISSUE THREAD

**Issue by cocoshe** [ShoufaChen/DiffusionDet#65]
https://github.com/ShoufaChen/DiffusionDet/blob/1efb36d4b0b721f2d509bc72656235a94d73ab02/diffusiondet/head.py#L350-L354

what does the "49" mean?

**Comment by ShoufaChen** [comment]
Hi,

Thanks for your interest.

49 means the flattened $7\times7$  RoI feature.

**Comment by cocoshe** [comment]
I notice the pooler, and find that it's from detectron2.
https://github.com/ShoufaChen/DiffusionDet/blob/1efb36d4b0b721f2d509bc72656235a94d73ab02/diffusiondet/head.py#L245
Then I find the `ROIPooler` class, and in its `forward` function, it returns **"A tensor of shape (M, C, output_size, output_size) where M is the total number of boxes aggregated over all N batch images and C is the number of channels in `x`."** So does it mean the `M` is `N * nr_boxes` which is the second dim of `roi_features`?

https://github.com/facebookresearch/detectron2/blob/80e2673da161f57afe37ef769836a61976108ef1/detectron2/modeling/poolers.py#L206-L220

**Comment by ShoufaChen** [comment]
Yes, you are right.

`N` is the batch size and `nr_boxes` is the number of boxes per image.

**Comment by cocoshe** [comment]
> Yes, you are right.
> 
> `N` is the batch size and `nr_boxes` is the number of boxes per image.

Thanks for your reply!
