### ISSUE TITLE
请问为什么单卡调试时会提示显存不够？

### ISSUE THREAD

**Issue by HappyLuffe** [ShoufaChen/DiffusionDet#69]
我是用的是3090进行调试，系统环境为Ubuntu。
在单步调试的过程中出现显存不够的报错，
报错的位置为：
<img width="595" alt="屏幕截图 2023-03-08 220548" src="https://user-images.githubusercontent.com/44888261/223734228-3bc52c42-4f59-4627-a3ca-5fec9c26b0c3.png">
具体报错为：
<img width="1566" alt="屏幕截图 2023-03-08 220734" src="https://user-images.githubusercontent.com/44888261/223734292-98486df1-6cc0-4b84-9764-bc5fa11bef89.png">

**Comment by LuohaoXu** [comment]
把配置文件里的 IMS_PER_BATCH 改小一点，比如改成1，显存应该就够了。
