### ISSUE TITLE
我的结果比论文结果平均低1.7，请问大家的结果怎么样？

### ISSUE THREAD

**Issue by Markkk111** [ShoufaChen/DiffusionDet#73]
![image](https://user-images.githubusercontent.com/126062944/226234415-90f9d0b7-46df-4fb6-8ecd-4b1c55f29088.png)

**Comment by ShoufaChen** [comment]
@Markkk111 

你好，请问你的具体setting是什么呢？我们已经提供训练好的checkpoint，是能够复现结果的。

**Comment by Markkk111** [comment]
您好，谢谢您的回复。我使用的自己训练的pth文件，还没有使用下载的checkpoint文件，等服务器闲下来再试试。gpu是8个NVIDIA GeForce RTX 3090。--config-file /configs/diffdet.coco.res50.yaml  --eval-only MODEL.WEIGHTS  /output/model_final.pth

**Comment by ShoufaChen** [comment]
请问你训练的启动命令是什么

**Comment by Markkk111** [comment]
python train_net.py --num-gpus 8     --config-file /configs/diffdet.coco.res50.yaml

**Comment by ShoufaChen** [comment]
能提供一下训练的log吗

**Comment by Markkk111** [comment]
[log.txt](https://github.com/ShoufaChen/DiffusionDet/files/11025098/log.txt)

**Comment by ShoufaChen** [comment]
你可以`git diff` 看一下代码的改动情况吗

**Comment by ShoufaChen** [comment]
log里的一些error有改动吗？
```
[03/15 20:57:27] d2.engine.train_loop ERROR: Exception during training:
Traceback (most recent call last):
  File "/home/name/anaconda3/lib/python3.10/site-packages/detectron2/engine/train_loop.py", line 155, in train
    self.run_step()
  File "/home/name/anaconda3/lib/python3.10/site-packages/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/home/name/anaconda3/lib/python3.10/site-packages/detectron2/engine/train_loop.py", line 287, in run_step
    loss_dict = self.model(data)
  File "/home/name/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/name/anaconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/name/anaconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/name/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/name/DiffusionDet-main/diffusiondet/detector.py", line 330, in forward
    loss_dict = self.criterion(output, targets)
  File "/home/name/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/name/DiffusionDet-main/diffusiondet/loss.py", line 264, in forward
    l_dict = self.get_loss(loss, aux_outputs, targets, indices, num_boxes, **kwargs)
  File "/home/name/DiffusionDet-main/diffusiondet/loss.py", line 226, in get_loss
    return loss_map[loss](outputs, targets, indices, num_boxes, **kwargs)
  File "/home/name/DiffusionDet-main/diffusiondet/loss.py", line 132, in loss_labels
    cls_loss = sigmoid_focal_loss_jit(src_logits, target_classes_onehot, alpha=self.focal_loss_alpha, gamma=self.focal_loss_gamma, reduction="none")
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: stride == cur_contig_stride || size == 1 || (still_rightmost && stride == 1) || (!still_rightmost && stride % word_size == 0) INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/executor_utils.cpp":623, please report a bug to PyTorch. Vectorization of T1_g[ iS145{( ceilDiv(( ceilDiv(( ceilDiv(( T0.size[0] * T0.size[1] ), 2) ), 1) ), 128) )}, iS144{1}, iS142{2}, iS146{128} ] with word size 2 not possible due to invalid stride. Domain: iS145{( ceilDiv(( ceilDiv(( ceilDiv(( T0.size[0] * T0.size[1] ), 2) ), 1) ), 128) )}, stride: 81
```

**Comment by Markkk111** [comment]
您好，改过了，正式开始正常训练的时间是03/16 15:06:53。

**Comment by ShoufaChen** [comment]
请问这个错误是因为改动了代码吗？能看一下`git diff`的情况吗

**Comment by Markkk111** [comment]
您好，我确实改动了部分代码，但是我还没用过git diff命令，等我下课回来后有发现再给您回复，谢谢您的帮助。

**Comment by ShoufaChen** [comment]
你好，请问发现了改动哪里吗

**Comment by Markkk111** [comment]
你好，我使用git diff命令显示大片空白，应该是哪里没有配置好，所以我先把我能回忆起来的改过的给您总结如下：
1、demo.py  line 47  #default="configs/quick_schedules/mask_rcnn_R_50_FPN_inference_acc_test.yaml",
        改为：default="/home/DiffusionDet-main/configs/diffdet.coco.res50.yaml",
2、train_net.py line 258     # cfg.merge_from_file(args.config_file)
    改为 cfg.merge_from_file("/home/DiffusionDet-main/configs/diffdet.coco.res50.yaml")
3、DiffusionDet-main\detectron2\datasets\prepare_ade20k_sem_seg.py line 19
改为： dataset_dir = Path(os.getenv("DETECTRON2_DATASETS", "/home/DiffusionDet-main/detectron2/datasets")) / "ADEChallengeData2016"

**Comment by Markkk111** [comment]
4、 DiffusionDet-main\configs\diffdet.coco.res50.yaml line 3
  改为：WEIGHTS: "/home/DiffusionDet-main/models/R-50.pkl"
  #WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"

**Comment by ShoufaChen** [comment]
你还，你该动的这些都不会引起上面的那个Error啊，请问你的Error怎么产生的以及怎么fix的

**Comment by Markkk111** [comment]
你好，谢谢您的回复，这个error是我用的Finalshell连接服务器运行的时候报错的，然后我用pycharm运行的时候这个error就消失了可以正常训练了，由于我的能力有限，具体原因是什么我也不清楚，pycharm可以运行之后我就忽略掉这个问题了。

**Comment by ShoufaChen** [comment]
你能clone一份新的代码重新跑一下吗，不要改动代码，直接跑

**Comment by Markkk111** [comment]
好的，谢谢您，我一会就试试，等有了结果再来回复您，谢谢您的耐心以及帮助，不胜感激。

**Comment by ShoufaChen** [comment]
请跑一份没有任何修改的代码。我先close了，你跑出来结果不对的请再reopen。

**Comment by Markkk111** [comment]
好的，谢谢！

**Comment by Markkk111** [comment]
您好，等等，demo.py line 47 #default="configs/quick_schedules/mask_rcnn_R_50_FPN_inference_acc_test.yaml",
改为：default="/home/DiffusionDet-main/configs/diffdet.coco.res50.yaml",
这个替换可以这么换吗？我没有找到mask_rcnn_R_50_FPN_inference_acc_test.yaml这个文件

**Comment by ShoufaChen** [comment]
这个文件训练用不到的，尽量不要有任何的改动

**Comment by Markkk111** [comment]
收到！
