### ISSUE TITLE
An issue about training the Net in VOC

### ISSUE THREAD

**Issue by sixone-Jiang** [ShoufaChen/DiffusionDet#75]
Thank you for your brilliant work! I'm really sorry to disturb your time. I have two Questions as follows:
First, I want to test your code in COCO, but I am really a freshman; how can I trained this model in VOC2012 with json annotations?
Second, I try to frozen your backbone Net, and then fine-turn your sparse head; but I don't know how to frozen it right.

**Comment by sixone-Jiang** [comment]
I also read the #20, but I can`t fix my problem.

**Comment by ShoufaChen** [comment]
Hi,

Detectron2 supports the VOC dataset. You can refer https://github.com/facebookresearch/detectron2/blob/main/configs/PascalVOC-Detection/faster_rcnn_R_50_FPN.yaml for your experiment.

**Comment by sixone-Jiang** [comment]
Thanks！
