### ISSUE TITLE
About the N_train problem mentioned in the paper

### ISSUE THREAD

**Issue by XiaoyuZxy00** [ShoufaChen/DiffusionDet#76]
Hello author, thanks for your work
I know that the N_eval setting of the inference stage is set by cfg.MODEL.DiffusionDet.NUM_PROPOSALS
But I haven't found the question about the N_train setting during training. Please tell me how to change N_train?
If you could answer my question, I would be very grateful!

**Comment by ShoufaChen** [comment]
Hi,

The `cfg.MODEL.DiffusionDet.NUM_PROPOSALS` at the training stage represents $N_{train}$.

**Comment by XiaoyuZxy00** [comment]
> Hi,
> 
> The `cfg.MODEL.DiffusionDet.NUM_PROPOSALS` at the training stage represents Ntrain.

Thank you for your reply! How to set the parameter of N_eval?

**Comment by ShoufaChen** [comment]
The `cfg.MODEL.DiffusionDet.NUM_PROPOSALS` represents $N_{train}$ at the training stage and $N_{eval}$ at the inference stage. Therefore, both $N_{train}$ and $N_{eval}$ are set by `cfg.MODEL.DiffusionDet.NUM_PROPOSALS`.

**Comment by XiaoyuZxy00** [comment]
Thank you for your patient answer, I have understood! Have a good weekend!
