### ISSUE TITLE
the number of batch size during infering

### ISSUE THREAD

**Issue by HaiLin545** [ShoufaChen/DiffusionDet#78]
Hello,

I noticed that the batch size support only 1 because the you select the first batch when do box renewal in you code. Can you explained it? 
Thank you.
![image](https://user-images.githubusercontent.com/56110784/227696360-10b5e280-e939-42b9-b99c-c92bc39036dc.png)

**Comment by ShoufaChen** [comment]
Hi, @HaiLin545 

Thanks for your interest.

 Detectron2 only supports batch size = 1 for inference as discussed https://github.com/facebookresearch/detectron2/issues/33. The above code only works at the inference stage so it also only support batch size 1.
