### ISSUE TITLE
Thought about Box corruption.

### ISSUE THREAD

**Issue by imabackstabber** [ShoufaChen/DiffusionDet#8]
Looks like only scaling operation is done in Box corruption for training stage, however by only scaling them, the `centers` of the boxes remain the same, but in inference stage, the boxes are generated totally randomly, which means that you have to adjust the center(maybe drastically) to make a box center right.
Is there any ablation studies about the Corruption method? (or they're already in the paper, i just missed it?)

**Comment by ShoufaChen** [comment]
Hi,

As illustrated in these [lines](https://github.com/ShoufaChen/DiffusionDet/blob/main/diffusiondet/detector.py#L395-L398),
both center coordinates and sizes (width and height) are scaled.

**Comment by imabackstabber** [comment]
> Hi,
> 
> As illustrated in these [lines](https://github.com/ShoufaChen/DiffusionDet/blob/main/diffusiondet/detector.py#L395-L398), both center coordinates and sizes (width and height) are scaled.

Code is very clear.Thanks for the prompt reply! I'm gonna close the issue.
