### ISSUE TITLE
Too many boxes in 

### ISSUE THREAD

**Issue by LuohaoXu** [ShoufaChen/DiffusionDet#81]
Hello! Thanks for your great working!
I run demo.py with --video-input. But there are too many boxes in the generated results. Please tell me what I should do.
![2023-04-01 10-23-29 的屏幕截图](https://user-images.githubusercontent.com/83861560/229261689-644ff7c2-6cbc-428c-8f82-c18f43e45e75.png)

**Comment by ShoufaChen** [comment]
Hi,

You could filter boxes by scores, ie., drop boxes with scores lower than a threshold, eg., 0.5.

**Comment by tanghua66** [comment]
> [LuohaoXu](/LuohaoXu)
Hi，I had the same question，Did you solved？

**Comment by LuohaoXu** [comment]
> > [LuohaoXu](/LuohaoXu)
> > Hi，I had the same question，Did you solved？

Adjust the threshold value in the detector.py. This problem can be solved.
<img width="491" alt="屏幕截图 2023-12-02 170055" src="https://github.com/ShoufaChen/DiffusionDet/assets/83861560/d8a63c99-7fc2-4ead-a4e9-9381d1d5fb0f">

**Comment by tanghua66** [comment]
> > > [LuohaoXu](/LuohaoXu)
> > > Hi，I had the same question，Did you solved？
> 
> Adjust the threshold value in the detector.py. This problem can be solved. <img alt="屏幕截图 2023-12-02 170055" width="491" src="https://private-user-images.githubusercontent.com/83861560/287433488-d8a63c99-7fc2-4ead-a4e9-9381d1d5fb0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTczMTIsIm5iZiI6MTcwMTY5NzAxMiwicGF0aCI6Ii84Mzg2MTU2MC8yODc0MzM0ODgtZDhhNjNjOTktN2ZjMi00ZWFkLWE0ZTktOTM4MWQxZDVmYjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEzMzY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZjE0MWViOTZiYmI0ZTY5MjJhMzBiMmVlOTMwYTU0MDE1MDM2MjFmMWVkNDRmMTUzNmY1NDk2ZGE5ZDk5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wYcqnPkGFfwjYwNrQjI53gSkapqgk5Q2ps4hrXdvtpw">

It doesn't work. Ps: train on my datasets. 
![)}L5NA6G0ENUINJF6O3TR(3](https://github.com/ShoufaChen/DiffusionDet/assets/139189156/87f9255a-bf3d-4a69-bfd1-e1170d114eb8)

**Comment by BrainPotter** [comment]
> > > > [LuohaoXu](/LuohaoXu)
> > > > Hi，I had the same question，Did you solved？
> > 
> > 
> > Adjust the threshold value in the detector.py. This problem can be solved. <img alt="屏幕截图 2023-12-02 170055" width="491" src="https://private-user-images.githubusercontent.com/83861560/287433488-d8a63c99-7fc2-4ead-a4e9-9381d1d5fb0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTczMTIsIm5iZiI6MTcwMTY5NzAxMiwicGF0aCI6Ii84Mzg2MTU2MC8yODc0MzM0ODgtZDhhNjNjOTktN2ZjMi00ZWFkLWE0ZTktOTM4MWQxZDVmYjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEzMzY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZjE0MWViOTZiYmI0ZTY5MjJhMzBiMmVlOTMwYTU0MDE1MDM2MjFmMWVkNDRmMTUzNmY1NDk2ZGE5ZDk5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wYcqnPkGFfwjYwNrQjI53gSkapqgk5Q2ps4hrXdvtpw">
> 
> It doesn't work. Ps: train on my datasets. ![)}L5NA6G0ENUINJF6O3TR(3](https://private-user-images.githubusercontent.com/139189156/287717261-87f9255a-bf3d-4a69-bfd1-e1170d114eb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDk1NzgsIm5iZiI6MTcxNTMwOTI3OCwicGF0aCI6Ii8xMzkxODkxNTYvMjg3NzE3MjYxLTg3ZjkyNTVhLWJmM2QtNGE2OS1iZmQxLWUxMTcwZDExNGViOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwMjQ3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWU4ZjZjN2EzZTRjNDdkMDJiY2FlNjA5ZDA2YzA5ZDc3MjBkODhjNDY3ZTNiM2FhNTYyNTI1YTk3ODNkYzg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eveV_rzwniejfsWYREFa0GrFlN3W5E8HxXjcljc_UBU)

Have you solved this problem? I ran the same one. I need your help.
